# Generated by Django 2.2.5 on 2019-09-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('NickName', models.CharField(max_length=50)),
                ('Sex', models.CharField(max_length=1)),
                ('bYear', models.IntegerField()),
                ('bMonth', models.IntegerField()),
                ('bDay', models.IntegerField()),
                ('dateReg', models.DateTimeField()),
            ],
        ),
    ]
