# Generated by Django 2.2.5 on 2019-10-04 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('NickName', models.CharField(max_length=50)),
                ('email', models.TextField(default=None)),
                ('password', models.TextField(default=None)),
                ('Sex', models.CharField(max_length=1)),
                ('bYear', models.IntegerField()),
                ('bMonth', models.IntegerField()),
                ('bDay', models.IntegerField()),
                ('dateReg', models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 4, 21, 32, 41, 431653))),
                ('status', models.TextField(default='0')),
                ('rank', models.TextField(default='1')),
                ('title', models.TextField(default='NoNe')),
                ('language', models.TextField(default='NoNe')),
                ('country', models.TextField(default='NoNe')),
                ('city', models.TextField(default='NoNe')),
                ('telephone', models.TextField(default='0')),
                ('groups', models.TextField(default='user')),
            ],
        ),
    ]
