# Generated by Django 2.2.5 on 2019-09-19 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20190918_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.TextField(default='NoNe'),
        ),
        migrations.AddField(
            model_name='users',
            name='country',
            field=models.TextField(default='NoNe'),
        ),
        migrations.AddField(
            model_name='users',
            name='groups',
            field=models.TextField(default='user'),
        ),
        migrations.AddField(
            model_name='users',
            name='language',
            field=models.TextField(default='NoNe'),
        ),
        migrations.AddField(
            model_name='users',
            name='rank',
            field=models.TextField(default='1'),
        ),
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='users',
            name='telephone',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='users',
            name='title',
            field=models.TextField(default='NoNe'),
        ),
        migrations.AlterField(
            model_name='users',
            name='dateReg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 19, 21, 58, 57, 369876)),
        ),
    ]
