# Generated by Django 2.2.5 on 2019-10-04 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20191004_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NickName', models.CharField(max_length=50)),
                ('BackGround', models.FileField(blank=True, default='default.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='dateReg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 4, 21, 41, 15, 922134)),
        ),
    ]
