# Generated by Django 2.2.5 on 2019-10-04 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20191004_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='BackGround',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='./../static/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='dateReg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 4, 21, 54, 39, 482833)),
        ),
    ]
